#! /bin/sh

sxhkd &
autorandr --change primary
lxpolkit &
# If HDMI-1 connected, split workspaces to both monitors
if [ "$(xrandr | grep "DP-0 connected")" ]
then
    bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
else
    bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 10
fi

# Used to make polybar maintain proper workspaces per monitor when going from 2
# to 1 monitor again.. This may include some monitor re-ordering issues
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config pointer_action1 move

# Sometimes when using an external monitor that is larger than the base laptop
# screen size, padding would be applied to make the nodes the size of the
# laptop resolution - we don't want that, as the nodes should fill out the
# entire height/width of the monitor, so we set all padding to 0.
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset

bspc config border_width       6
bspc config border_radius      6
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill ~/Documents/Wallpapers/waifu.jpg
# Reload .Xresources
bspc config border_radius 12
# Launch polybar
sh ~/.config/polybar/launch.sh --docky
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
betterlockscreen -u ~/Documents/Wallpapers/gruvbox.png
# ------- Autostart apps ------
# Picom
picom --experimental-backend &
# Dunst
dunst &
# Dropbox

# Cmst (connman front-end)
# cmst &
# network-manager-applet
nm-applet &

# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
ibinput-gestures-setup start
# Xinput configs (touchpad)
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0
setxkbmap -option
setxbmap -layout "us"
pipewire &
