#! /bin/sh
if [ "$(xrandr | grep "DP-0 connected")" ]
then
    bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 
else
    bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 
fi

# Used to make polybar maintain proper workspaces per monitor when going from 2
# to 1 monitor again.. This may include some monitor re-ordering issues
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config pointer_action1 move

# Sometimes when using an external monitor that is larger than the base laptop
# screen size, padding would be applied to make the nodes the size of the
# laptop resolution - we don't want that, as the nodes should fill out the
# entire height/width of the monitor, so we set all padding to 0.
bspc config top_padding 22
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config active_border_color "#de83c6"
bspc config focused_border_color "#de83c6"


bspc config border_width       1
bspc config border_radius     6 
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Xinput configs (touchpad)
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0

xsetroot -cursor_name left_ptr
sh ~/.config/bspwm/autostart.sh &
#wal -R
sh .config/bspwm/rules
